-- Your SQL goes here
CREATE TABLE IF NOT EXISTS students (
  id int AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(60),
  age int,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
